steps:
  - label: "Julia {{matrix.version}} -- {{matrix.benchmark}}"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
    matrix:
    setup:
      version:
        - "1.9-nightly"
        - "nightly"
      benchmark:
        - "A"
        - "B"
    agents:
      queue: "juliaecosystem"
      exclusive: true
      arch: "x86_64"
    commands: |
      echo "--- Instantiate"
      julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.build()'

      echo "+++ Run benchmarks {{matrix.benchmark}}"
      julia --threads=auto --project=. run_benchmarks.jl {{matrix.benchmark}} all
    artifact_paths:
      - "results.csv"

    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60