name: Benchmarks

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Julia ${{ matrix.version }} -- ${{ matrix.benchmark }} -- ${{ matrix.category }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: "!contains(github.event.head_commit.message, '[skip tests]')"
    strategy:
      fail-fast: false
      matrix:
        version: ["nightly"]
        benchmark: ["serial", "multithreaded"]
        category: ["all"]
        include:
          - version: "nightly"
            benchmark: "slow"
            category: "bigint"
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - name: Instantiate
        run: julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.build()'
      - name: Run benchmarks ${{ matrix.benchmark }}
        run: julia --threads=auto --project=. run_benchmarks.jl ${{ matrix.benchmark }} ${{ matrix.category }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: results-${{ matrix.version }}-${{ matrix.benchmark }}-${{ matrix.category }}
          path: results.csv
          if-no-files-found: ignore
